[package]
name = "ffi_qrcode"
version = "0.1.1"
authors = ["zhoutianliang <mfkgdyve@gmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
[lib]
name = "ffi_qrcode"
crate-type = ["cdylib"]
path = "src/lib.rs"

[[bin]]
name = "ffiqr"

[build-dependencies]
cbindgen = "0.26.0"

[dependencies]
qrcode = "0.14"
image  = "0.25.1"
hex = "0.4.3"
rqrr = "0.7.1"

