name: Split Monorepo

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  split_monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - 'ffi-lac'
          - 'ffi-ocr'
          - 'ffi-opencc'
          - 'ffi-pinyin'
          - 'ffi-qrcode'


    steps:
      -
        uses: actions/checkout@v2

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.3.0

        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'TianLiangZhou'
          repository_name: '${{ matrix.package }}'
          user_name: "TianLiangZhou"
          user_email: "mfkgdyve456@126.com"
          branch: "master"

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: 'TianLiangZhou'
          repository_name: '${{ matrix.package }}'

          # ↓ the user signed under the split commit
          user_name: "TianLiangZhou"
          user_email: "mfkgdyve456@126.com"
          branch: "master"
